### ISSUE TITLE
Use used_blueprint instead of blueprint when saving and loading results

### ISSUE THREAD

**Issue by vnuotio** [ProjectCED/CED-LLM#165]

**Comment by janivanhala** [comment]
Inspected and tested various things. Used_blueprint handling looked weird as it didn't really use graph database features.

[This branch](https://github.com/ProjectCED/CED-LLM/tree/Temp-used-blueprint-fixes) changes to look through relationship instead of property value. And added new function to get whole used_blueprint

**Comment by janivanhala** [comment]
This will be solved in #186
